version: '2.1'

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:0.12.6
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
